### ISSUE TITLE
Update Scores

### ISSUE THREAD

**Issue by priyanshisharma** [anshsrtv/leaderboard-project#16]
Update score variable of the leaderboard model. 
You may use variables for values to do the same instead of hardcoding it if the schema isn't clear yet, such that we will be able to simply update values of those variables later.

**Comment by anshsrtv** [comment]
I didn't get it.. :thinking:

**Comment by priyanshisharma** [comment]
I mean
1. Initialise variables `gfi_score = 10`, `medium_issue = 20`, `hard_issue=40`
2. If a good first issue is being resolved, `score+=gfi_score` and so on for medium and hard issues. (This can be done in the `issue` view. )

So when the weights for different issues are updated finally, we can simply change the values of variables initialised in step 1.

**Comment by anshsrtv** [comment]
Yeah good idea :+1:

**Comment by priyanshisharma** [comment]
Yeaahh ✌️, we can also separate other sensitive stuff to the `.env` file. Shall we raise a separate issue for it?

**Comment by anshsrtv** [comment]
> Yeaahh , we can also separate other sensitive stuff to the `.env` file. Shall we raise a separate issue for it?

Yeah, a new issue can be raised if needed... :+1:
