### ISSUE TITLE
Sign up with Github

### ISSUE THREAD

**Issue by anshsrtv** [anshsrtv/leaderboard-project#21]
Social Login using Github OAuth needs to be integrated.
1. This will be the only way to register on the platform for now..
2. Django signals to create a new leaderboard object whenever a new user registers.

**Note** : Whoever takes up this issue, please specify in `/docs/` which APIs are for webhooks in `operation_id` of APIs

**Comment by priyanshisharma** [comment]
I was wondering that if we make a leaderboard object as soon as a new user registers, we'll see 0 PRs 0 merged PRs etc. for all the people who have registered and done nothing in the leaderboard. Should we be creating an object when the user makes their first PR instead..?

**Comment by anshsrtv** [comment]
I think that wont be a problem because they will be added at the end of the leaderboard as in any other leaderboards... :thinking:

**Comment by priyanshisharma** [comment]
Yeah okay cool.. 🙌
