### ISSUE TITLE
Update rest of leaderboard variables

### ISSUE THREAD

**Issue by priyanshisharma** [anshsrtv/leaderboard-project#8]
It is required that we update the other variables of leaderboard as well:

1. Check for label of issue resolved on merging of a PR and accordingly set boolean `good_first_issue` and increment `medium_issues_solved` and `hard_issues_solved` counters.

2. Also update `milestone_achieved`  when the milestone is achieved, i.e. 2 medium 1 one good first issue have been solved. Add `milestone_achieved` and make migrations if it doesn't already exist.

3. Leave `points` until we decide the weightage of the labels.. :wink:

**Comment by anshsrtv** [comment]
@priyanshisharma I think its better if we create a new Issue API for updating scores... :1st_place_medal: 
This will be easier i suppose.. :v:
